name: nammadaiva_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  fluttertoast: ^8.2.6
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  http: ^1.5.0
  focus_detector: ^2.0.1
  shimmer: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Correctly indented assets section
  assets:
    - assets/loginImage.png
    - assets/temple.png
    - assets/donation.png
    - assets/onlineseva.png
    - assets/ritual.png
    - assets/sevaimg.png
    - assets/transaction.png
    - assets/wowtracker.png
    - assets/audit.png
    - assets/logout.png
    - assets/backbutton.png
    - assets/phone.png
    - assets/message.png
    - assets/map.png
    - assets/about.png
    - assets/event.png
    - assets/otpimage.png


  fonts:
      - family: Nunito
        fonts:
         - asset: assets/fonts/Nunito-Regular.ttf
         - asset: assets/fonts/Nunito-Bold.ttf
           weight: 700
         - asset: assets/fonts/Nunito-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Nunito-Medium.ttf
           weight: 500
         - asset: assets/fonts/Nunito-Light.ttf
           weight: 300
